package com.ercoding.foodify.domain

import kotlinx.serialization.Serializable
import java.util.UUID

@Serializable
data class NutritionEntry(
    val id: String = UUID.randomUUID().toString(),
    val meal: String = "",
    val emoji: String = "",
    val createdAt: Long = System.currentTimeMillis(),
    val calories: Double = 0.0,
    val protein: Double = 0.0,
    val fat: Double = 0.0,
    val saturatedFat: Double = 0.0,
    val unsaturatedFat: Double = 0.0,
    val carbohydrates: Double = 0.0,
    val sugar: Double = 0.0,
    val fiber: Double = 0.0,
    val salt: Double = 0.0,
    val cholesterol: Double = 0.0,
    val sodium: Double = 0.0,
    val potassium: Double = 0.0,
    val vitaminA: Double = 0.0,
    val vitaminB6: Double = 0.0,
    val vitaminB12: Double = 0.0,
    val vitaminC: Double = 0.0,
    val vitaminD: Double = 0.0,
    val vitaminE: Double = 0.0,
    val vitaminK: Double = 0.0,
    val folicAcid: Double = 0.0,
    val calcium: Double = 0.0,
    val iron: Double = 0.0,
    val magnesium: Double = 0.0,
    val zinc: Double = 0.0,
    val phosphorus: Double = 0.0,
    val selenium: Double = 0.0,
    val copper: Double = 0.0,
    val manganese: Double = 0.0,
    val omega3: Double = 0.0,
    val omega6: Double = 0.0
)

fun NutritionEntry.toDisplayList(): List<Pair<String, String>> = listOf(
    "Kalorien" to "${calories.toInt()} kcal",
    "Eiweiß" to "${protein.toInt()}g",
    "Fett" to "${fat.toInt()}g",
    "Gesättigte Fettsäuren" to "${saturatedFat.toInt()}g",
    "Ungesättigte Fettsäuren" to "${unsaturatedFat.toInt()}g",
    "Kohlenhydrate" to "${carbohydrates.toInt()}g",
    "Zucker" to "${sugar.toInt()}g",
    "Ballaststoffe" to "${fiber.toInt()}g",
    "Salz" to "${"%.1f".format(salt)}g",
    "Cholesterin" to "${cholesterol.toInt()}mg",
    "Natrium" to "${sodium.toInt()}mg",
    "Kalium" to "${potassium.toInt()}mg",
    "Vitamin A" to "${vitaminA.toInt()}µg",
    "Vitamin B6" to "${"%.2f".format(vitaminB6)}mg",
    "Vitamin B12" to "${"%.2f".format(vitaminB12)}µg",
    "Vitamin C" to "${vitaminC.toInt()}mg",
    "Vitamin D" to "${vitaminD.toInt()}µg",
    "Vitamin E" to "${"%.1f".format(vitaminE)}mg",
    "Vitamin K" to "${"%.1f".format(vitaminK)}µg",
    "Folsäure" to "${folicAcid.toInt()}µg",
    "Calcium" to "${calcium.toInt()}mg",
    "Eisen" to "${"%.1f".format(iron)}mg",
    "Magnesium" to "${magnesium.toInt()}mg",
    "Zink" to "${"%.1f".format(zinc)}mg",
    "Phosphor" to "${phosphorus.toInt()}mg",
    "Selen" to "${"%.1f".format(selenium)}µg",
    "Kupfer" to "${"%.2f".format(copper)}mg",
    "Mangan" to "${"%.2f".format(manganese)}mg",
    "Omega-3" to "${"%.1f".format(omega3)}g",
    "Omega-6" to "${"%.1f".format(omega6)}g"
)